import Head from "next/head";
import estilos from "@/styles/Home.module.css";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   
      <div className={estilos.page} >       
        <h1 >Projeto da ótica em React/next sem appRoute na instalação</h1>
      </div>
    </>
  );
}
